import { FileText, Download, Eye, CheckCircle } from "lucide-react";

const SamplePreviewSection = () => {
  return (
    <section id="examples" className="py-24 px-4 bg-white relative overflow-hidden">
      {/* Background Decoration */}
      <div className="absolute inset-0 opacity-30">
        <div className="absolute top-20 left-20 w-96 h-96 bg-gradient-to-br from-cyan-200 to-blue-200 rounded-full blur-3xl" />
        <div className="absolute bottom-20 right-20 w-96 h-96 bg-gradient-to-br from-purple-200 to-pink-200 rounded-full blur-3xl" />
      </div>

      <div className="max-w-7xl mx-auto relative z-10">
        {/* Section Header */}
        <div className="text-center mb-16">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-100 border border-purple-200 mb-6">
            <Eye className="w-4 h-4 text-purple-600" />
            <span className="text-sm font-semibold text-purple-900">See It In Action</span>
          </div>
          <h2 className="heading-section mb-6">
            Sample Documentation
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Check out a real example of documentation generated by Git2Doc.
            Professional, comprehensive, and ready to use.
          </p>
        </div>

        {/* Preview Cards */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-16">
          {/* Markdown Preview */}
          <div className="group relative">
            <div className="absolute -inset-0.5 bg-gradient-to-r from-indigo-500 to-purple-500 rounded-2xl opacity-20 group-hover:opacity-30 blur-xl transition-all duration-500" />
            <div className="relative bg-white rounded-2xl p-8 shadow-xl border border-gray-200 hover:shadow-2xl transition-all duration-500">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                  <div className="p-3 rounded-xl bg-gradient-to-br from-indigo-100 to-purple-100">
                    <FileText className="w-6 h-6 text-indigo-600" />
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-900">Markdown Output</h3>
                    <p className="text-sm text-muted-foreground">content.txt</p>
                  </div>
                </div>
                <div className="px-3 py-1 rounded-full bg-green-100 text-green-700 text-xs font-semibold">
                  Generated
                </div>
              </div>

              <div className="bg-gray-50 rounded-xl p-6 font-mono text-sm space-y-3 border border-gray-200">
                <div className="text-indigo-600 font-bold"># Git2Doc: AI Documentation Generator</div>
                <div className="text-gray-700">## Overview</div>
                <div className="text-gray-600">Git2Doc automatically generates comprehensive...</div>
                <div className="text-gray-700">## Features</div>
                <div className="text-gray-600">- AI-powered repository analysis</div>
                <div className="text-gray-600">- Automatic workflow diagrams</div>
                <div className="text-gray-600">- Professional PDF export</div>
              </div>

              <div className="mt-6 flex items-center gap-3">
                <CheckCircle className="w-5 h-5 text-green-600" />
                <span className="text-sm text-muted-foreground">Properly formatted with headings, lists, and code blocks</span>
              </div>
            </div>
          </div>

          {/* PDF Preview */}
          <div className="group relative">
            <div className="absolute -inset-0.5 bg-gradient-to-r from-purple-500 to-pink-500 rounded-2xl opacity-20 group-hover:opacity-30 blur-xl transition-all duration-500" />
            <div className="relative bg-white rounded-2xl p-8 shadow-xl border border-gray-200 hover:shadow-2xl transition-all duration-500">
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                  <div className="p-3 rounded-xl bg-gradient-to-br from-purple-100 to-pink-100">
                    <Download className="w-6 h-6 text-purple-600" />
                  </div>
                  <div>
                    <h3 className="text-xl font-bold text-gray-900">PDF Export</h3>
                    <p className="text-sm text-muted-foreground">technical_documentation.pdf</p>
                  </div>
                </div>
                <div className="px-3 py-1 rounded-full bg-purple-100 text-purple-700 text-xs font-semibold">
                  16.4 MB
                </div>
              </div>

              <div className="bg-gradient-to-br from-gray-50 to-gray-100 rounded-xl p-6 border border-gray-200">
                <div className="bg-white rounded-lg p-6 shadow-inner space-y-4">
                  <div className="h-3 bg-gradient-to-r from-indigo-600 to-purple-600 rounded w-3/4" />
                  <div className="h-2 bg-gray-200 rounded w-full" />
                  <div className="h-2 bg-gray-200 rounded w-5/6" />
                  <div className="h-32 bg-gradient-to-br from-indigo-50 to-purple-50 rounded-lg border-2 border-dashed border-indigo-200 flex items-center justify-center">
                    <span className="text-xs text-indigo-600 font-semibold">Workflow Diagram</span>
                  </div>
                  <div className="h-2 bg-gray-200 rounded w-full" />
                  <div className="h-2 bg-gray-200 rounded w-4/5" />
                </div>
              </div>

              <div className="mt-6 flex items-center gap-3">
                <CheckCircle className="w-5 h-5 text-green-600" />
                <span className="text-sm text-muted-foreground">Professional PDF with embedded diagrams at 300 DPI</span>
              </div>
            </div>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
          <div className="text-center p-6 rounded-2xl bg-gradient-to-br from-indigo-50 to-purple-50 border border-indigo-100">
            <div className="text-4xl font-bold bg-gradient-to-r from-indigo-600 to-purple-600 bg-clip-text text-transparent mb-2">
              100+
            </div>
            <div className="text-sm text-muted-foreground font-medium">Lines of Documentation</div>
          </div>
          <div className="text-center p-6 rounded-2xl bg-gradient-to-br from-purple-50 to-pink-50 border border-purple-100">
            <div className="text-4xl font-bold bg-gradient-to-r from-purple-600 to-pink-600 bg-clip-text text-transparent mb-2">
              8
            </div>
            <div className="text-sm text-muted-foreground font-medium">Workflow Nodes</div>
          </div>
          <div className="text-center p-6 rounded-2xl bg-gradient-to-br from-pink-50 to-rose-50 border border-pink-100">
            <div className="text-4xl font-bold bg-gradient-to-r from-pink-600 to-rose-600 bg-clip-text text-transparent mb-2">
              300
            </div>
            <div className="text-sm text-muted-foreground font-medium">DPI Resolution</div>
          </div>
          <div className="text-center p-6 rounded-2xl bg-gradient-to-br from-cyan-50 to-blue-50 border border-cyan-100">
            <div className="text-4xl font-bold bg-gradient-to-r from-cyan-600 to-blue-600 bg-clip-text text-transparent mb-2">
              &lt;30s
            </div>
            <div className="text-sm text-muted-foreground font-medium">Generation Time</div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default SamplePreviewSection;
